### ISSUE TITLE
Aliases support

### ISSUE THREAD

**Issue by FGRibreau** [FGRibreau/common-env#5]
e.g.

```
.getOrElseAll({
 my:{
  key:{
   // specify the default value this way:
   $default: VALUE,
   // (optional) specify one or more aliases for this key
   // the order order of evaluation will be as follow 'MY_KEY' then 'ADDON_MY_KEY' then 'MY_SECOND_KEY'.
   // The first environment variable that yield a value will be used
   $aliases: ['ADDON_MY_KEY', 'MY_SECOND_KEY']
  }
}
});
```

**Comment by Freyskeyd** [comment]
J'aurai mis ça en dehors de la configuration de base.

``` javascript
var aliases = {
  'RABBITMQ_HOST': ['SOME_OTHER_KEY', 'SOME_OTHER_OTHER-KEY']
};

env.aliases(aliases)
  .getOrElseAll({
    rabbitmq: {
      host: 'localhost'
    }
  });
```

**Comment by JulienBreux** [comment]
@Freyskeyd :+1:

**Comment by FGRibreau** [comment]
@JulienBreux (je copie ici notre discussion avec @Freyskeyd)
la première approche est **déclarative**, la seconde utilise du **code** pour déclarer.

C'est la différence entre package.json et un scala sbt. L'un peut servir de brique initiale pour construire par dessus, l'autre non (on peut parser facilement un package.json mais pas un scala sbt).

Autre avantage on peut créer un helper `.aliases` qui étends l'objet :)

Note aussi (tu m'en as parlé IRL) que tes amis rubyistes déclarent leurs variables d'environements dans un YAML, c'est du déclaratif, même logique :)
