### ISSUE TITLE
Valid support for arrays or objects

### ISSUE THREAD

**Issue by FGRibreau** [FGRibreau/common-env#6]
`[]` are not supported, maybe use something like _0_, ... ?

**Comment by Freyskeyd** [comment]
This issue can be close due to latest release i think.

**Comment by FGRibreau** [comment]
Sadly this one is not related with https://github.com/FGRibreau/common-env/issues/10 because common-env still does not support array of objects and can't read arrays from environment variables, that's why this issue is still there :)

**Comment by FGRibreau** [comment]
API idea:

```
ENRICHMENTS__0_OUTBOUNDFILTERS__0_ROLE_NAME
ENRICHMENTS__1_OUTBOUNDFILTERS__0_ROLE_NAME
```

for 

```
ENRICHMENTS[0]_OUTBOUNDFILTERS_ROLE_NAME
```

because `[0]` is encoded as `__0` for the lack of a better alternative
